language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
after_success:
- docker run -p 8081:80 -d $DOCKER_USERNAME/se234-lab10-client:latest
service: docker
env:
  global:
  - secure: IlbN+UA1ed8hGeBQYM9fptwQQHLr9Zz+NpmcU1U9aGSghZoRWXDfZwIGHLfbXcfjuRd0TtKYRljZBWsi/aMccrc3Jbwzou5FGAFaqEQUHJXva2WsUJCBVGqVodXpHlkeMrWLNVilnwtEz8wJsi3r+NexQq7Cg7WUO2PfVOxz0QptyaaQgYU6Kblk6LHO4hfI57D69kXpDJP/Ut3Iv7+7aMJSjmDotqqDboOL3MDTZWMPvSCDikT68ZKhrbm1vwY1aRje/dOThoaxnd8lCEdRh8/KfSFzwPrp9/E9/XOBjRIrneOMNS5Hug+S3FiNgL6AcCqIqpZEfm3zXFzF/kNrMGRuf5M2ycPjREuxx8F4QW4e4TLNhds+gam5GZOcM8DbTmFyCnpajcOMz+3016kVLQTdMvCuZw4R8gL8ZBZmDcJ3mKwlf/NK/S2qleYwAh/CTVWlXqbhw40GtJi6U9YtmKdtbFYGrAfEhV+dK744ur0xKRbC2VsXZ8NrpZFUjMNcmARXZqFxMazjplO1GHzbqIVK68l04qZB8Th77Jai/4kVPfb8Q7oj7hcvDi7fkWa33de7wt2TgU0q5vmBROPkZFO5WyB+9CuVoMDOrdjt7nbxFExLiztz9SAEAzGp/BXLZjVL3WlLc2AJ/U2+BlC/kvOEfBQrwPpAMAK6ZVMFr2g=
  - secure: Hi0M8nWdw7pD/14ArVnNBc/X7tpukq+d+x/yr1IuU/Tjnt4ndmNBCxYaYnfl8WtvFQ+4PSgRvrTn+Y7b3R8qUqOGAemJ1hBUaTNE4eLCd2Yro9AqoE/8OmAkqHxLvUHNNfXwaPT+O3mInNSNGGQPnp+lrPIV70t/nVrd1XulM0Ls5L/7ttkYhtD/lb3lEo3fTNP4bsKmQ/TnXR59QsKkW9Nm0kB13gOXh7lR1l8LJRFI6toxWvD1WVLn/OZ4vSpdTp2ipSgEYmwPSZXnyhWCRAPwEoB+n4lHDe73E8fv7uhFwuyzSTzZ7pqor1i8D39hqPYN2o38XxFRA5zaVXlDArhYkWiMz1fTjJ64s2a5B1wtUEsXKwSXNHyolhCRn8PQ+E3QbH96eFkKXVZFXLy41uQ81vWn92wud7sLwX/n+WXfT7H51lIMYEkahcQOW5Ftwhnk32DuP46A71k1ffB+TT9uZKAg9VqAumFUH8Qhx8fa0iPgmMgxNCgmK/UkXuJz7zCw5I/x1IAy/M7fN8zBTye/mBunMOjtGRvWouxJMCNRO9rsm/D/obJkNETMyGAQ5toLfNgSwiwL23qLnKuvMESaWbcZAdaX40U2eYkHmyc77BfctVEEfSfthG6+MQcKXjap8yPsQYkBPf3i+EUTsolBVh58Hs7mJN8F1oEOr/k=
  - secure: Ix5QQtnPDm63zQYQ64cJyAmXV6ipcgBVv91fN4z6pq20jHz1SXu2rlbhsTNNvOn0St26hfTedTZ5/YMPwsSENmkiuOldRub+kVwMm5vA/O3rz3BJl+2jw8zUZ1CasDGllaH8XnXSpGB4KiJqIpDXER48ItS/PlRiGkjioFtAthkjgWweHT20idIhcS/w0h6W7eQrdApO8hlWOGEpCLZ9RggDUJcZFZkQrQHRRw52koWW9Blx9IEwuF/bma83DAgrBZYtxxkEbHXuYZIEbdB7LSM5V8m6GMuu1WSNnC55I4IyqJy8wZ5cHvb/04T/h0F+La2+Ej/yTpmuSJ+lpGB85qpZDxnUHY7WMS+fz64zMZQgVHxuCTy9/mVWz1jBp+J88m3ApyOOqiflppfzqVArHgL+36DZNbjlqjV49/ox9YQQwWguRYwQWyoZQyN2CdCX8XZkj6wppYSOIM4fG0oAHG3LvNLuYJ3xuD8y/+h+AETQn0uT0ta7V/5x/VdzTR6bs6vW+Ppy8i0cMlPY+Ikt8A7SztX128khvRTQmleZE4cexcmjEsx34/txPlS/cGWxR43qYgkSmg7jSnvb8z1WfuLWC/UpfxyOIiMgt44FOeBi7Ob2WIAtzSrb8iERmdhKbkFjnYRrdAvxx4vllXpUo8BTvizu0EjMed1yQBd1XqU=
