language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
service: docker
env:
  global:
  - secure: do07lvNGqh7wqX5Jr8ncWldI2XLwtnDy+1R0zn/Q5AveJ/3DSEdbYVtfpPdhAV6vcAB56x4Q2tMDRcSylt4LL8c1kNbzR20LRzs9RTp99NO1YX3wgFb4vGCDke7xPxQtYiCxmMUk4LaR8qs1NKo23ovGSs35aXPY++Igrc3uGQ42tS1E7WKE3psM09YiJFduH4ppZJAhD2TOStQtI+YkV57iqa/jN9RCcznQS803LDCVXAVy0esaFl+X+KQdaimBMW1EP+Uj5l4CCw96khotmILHwPofpbR7JszqvTnoryJ3lGfc5ksjWSiLmfF+7WnxV9zdG6cw9JOQJAdO6Fr4O3hms//s0OTChLCjtd8233QJMT4v+L6qz4+ExPNT36UZLwDR2wn+JiGFA2rG/UAxLxebwshTOcL+Gv1bSI4FxwqTNbQc3b6jc/OAtTvW1RrRQm/SsxXl0yW70X6JK9nDqPLQbkPKlMl0ApfMwWrBwH8ZMzxHNT/m+1xPF+Y6dKTFnZ1BlGpUr1b/WMrcOEIDYraRuvJKBVGDLcaSeqeEEIBgnuCZv2pezvsFc4bxpPqvhK/Xi94O6f+Li2t+S6cm3Dp+JONivL3hPnKtC61oPfvauZvsz2+CzhyNTrXkbNnkIvsL5eYQMmN9pt7iP0yRq1oyPCMs/mzfJsOlWWQWwcw=
  - secure: LEz7DT52R/kklWfwlO3Rdz5CR8vekmAOoFdBa6+1dG6wcEP0wa5O7/mA5S2V5clJV/gvUO1SaBaEa/BnAiUXX13K9Zdg/DTQYtn1BassJpviWVd5b3GTsCGABOwm/DNN6/woltx4WcOccxCUfPh3uYOQ7SBachufagu/Lr3679TSDABIhG51W9z4w3envVr3fJQdmMftk3789DSdqkMmKWb/CbcCcNe+cb4mm1RrB7Nc2p/xAFqHpKgmKhVkQXPSKrIioW0oHnWthww6n0DpKWRKCczg3VcbF5euFxPOab3ljYnyjlcsvX4aqR8VtQWRmTabNxrbjAqjY1XbfnFdGrlAcre1qFBN+9Q6DyZkmhi5fBSr+rjAuzphWOcu5QVVATCZ42z2ruTbyHsUmG/3EfJGQfG04RM04KXh6oeeIOBH4egwlTIA1c4geNzkUx7cYw54Dgs7cEwGq9FnlvNhdkxMLhEPvR/lzt4RMu/z/ENMuP0tuUroN1OYBk1mPX8zQhKSoFtmOwAv4q+WCWIFe09ggVq0zVdflMlJpNZIwzJAJL1u1ZKXKbpQzwixj6+49S4wVTHwcHIn7rx2ExrC4v65GaapwfXDQmRu5e5J38D5KAkCXiiKaYF40LX9h2IaAJx0C+Bs3Dff7BNYYLK1x9iGlaUJJc6an4Pkg5IcB0E=
  - secure: DjVWmz8yw8wI02YDmCqKTghmq2vOQI678iuRFCvLCr1G+qfVXPWdCOpVM2K571G1zCp5voGCZ7IqXfaWt7JDttC5ZZz5bxdf1+PlvS4bXZ7hnyWadS6ea3wxWb/l553/EjO08GSK0t0N6t4D/N2OrIcksfhl/FZ2gFOJ2DyZyAYCd2BTBnqcOBVATIx7LlTMfY3gSFPMBCokoakXuiX2Z5SjAqcaggUBoPYVH1zLLDxzBUShcl1xzvwMYS460ahJVeSbmRmURaeZ9jGA6i0U7CXrw5ggx9+QQJbDddzy+CjUtOKt+y6A7Bm34BSOMiWo2fzaYFq/jfdLFVLfcdBZE4lcLh01QebgcG5CWGeHTQI7M/EZ0XZZiwcmG+J8kswFK2hJ+Mi7S8Ybt6uazhimNWNdMPT9b4Tl4ACSl7QvaW3/81JJEQmsHp9tcpcnfqMFFhTt+qQowYIaiwI+NnFrsmYtpVHaU0BqEF7xJGa0E/B3gAVBaj29vXs3N9VuHjhj1MFidrpxz5t4AYickTk+iB/Fjk+xXKBTFzVxIMniK+NqG/NDDgAlY1BE3VG/gwczOO/mEqoEnzA+tg51YAaFOnGx06AkkEYgcXvn75s9jM2pCZubcU4X4yQYxOdomnCVRduYJNqAIj/SP60EllOSl+ucaEqOlmfSxPElWJwjV6U=
