language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
after_success:
- docker stop htmltest
- docker rm  htmltest
- docker run -p 8081:80 -d $DOCKER_USERNAME/htmltest:latest
service: docker
env:
  global:
  - secure: iQFFlPHolTalTabD95RaaGn0mQhugpHJeUIEE3FCP6QVs7MM+PH2Lli0PA7f9RcWqfpHIcsRB0ZYRMmfXd9whSwy2+Ti9dmb7BT7iJ9x8mGB2qyxHlt7mbZn/4QO85NSjRHkD0y2LdVjEHwABIc2crMH8Q4Ne51rBBGyZKZVNhkv+2GHk9lewjAZE4Uq9ExLew6nGljm+EkQ48lApMMo2Aab9FGBtvpQPZ0DqjWzrm0e6zSRprRfwDRbFtlgd4egGdxscyovc+qqPuAbvC/U4y5I9UCOn8H3I9n2ZXakXRabzW3ttrUnaJKnAE5ANX5oCig9e8tfeJQgAwL58/9EiKu+T860A5H1h+Megr8dQX3XvUhyw3nh+x++c+Exd0TwPTEa4eMUC8ctstNubSMmAp51DKk/hKoiiPrnh+JCDmWuiCtMOQHXscJZDk5TIhBN9Yb4jP8lasQu74X2OVrSgN0sSOeYdwb1nq0O2gPmZOYSAVIRefiPGuUmmFYc4TvNuz/9/8wyTDwYVBvBpBWdM2H5x3jMlQG6zJAIqnfYsoQV5WlNDBAKhvwE0HOuohoVH+c9TS2Y3bR1SiTDKImBYlvroLG+LfgyckPuzIHhQOe/G/xesrM5E0Kf2F+lHbu2i+TOCunZUQRmTOhU41vxvfom+GVkumIO0p5+q4y6uqE=
  - secure: COWVBzyRwdSR/TdBtF+xmM1gxNT3g7j9v4ZqjOjXIMLDdQGDATMadq7YhTzXwGmCOl8hiM3bsIdNdBUDz3qlznYh1KknQet5u1nN62ZQ+61AYR3jyrI7PCcOK9Ak6ayCFuEInF67FK6hKrGkuAGCEv4NjJIhlb5vb6miwcnb3nB3nq5/nwvEdukNYx/W/A7hoNQG+bSrIZEVI26lszSBIPW+VSQ4KvQfzJh2/hKYc1INv9dx/UQdl0By+3bIH7aLkgogCYHriEV3+V9IYggbeLQMSlKuwAeEW7NmnAz6LqH9XKRCPpsEHwHlxZhuSASXizmxlnP9A4lrjkexQ2fbIpkMvbabKY3EFHNb+sfQMSdu9R+/bvyQd4gzTcmRCZU8CUslNp8TuJgH1kj+xZ/tdu9+dRP0iQZtBdO1AvixwXwtSl8BnWyzhx93VTYxw6KpNTWLINq9z3P4s89BEeu18J7Ivxbc5azp/+6m5GD1DRn9ey5yAbsc8clGwX41PovOXhdCDZlsfQ+sZbNXXyCRr+U8g/Y7MUM2uPgsHSFdbI9NyDQnpo42CokpE62+A2mSIEwFvjeoERT86OMnYUXZntlBfAhUp48V7PdCANjVrXlsOyn86KzRUfvlJToV60sZ/8ah4ir/tfT/y07xcZSxVLKLH0PyNpz/DuIulCBVDYc=
  - secure: c4Go8vGeGSnsbTpO/0zxW2raQXNLUluFqWe7kDWLCHUZEzA6fbGUHwNu65u6kLDWijgdtAJ+PiqUkQST4QdjWsbtBBWf7NwIW92UEWE593FApWN8bal3P43HluZeYuVc9Zlm3PXL2z//dM/ElGuiG2auv//nqFIlkW8fRY+0d7+wnWGaGlo+fV11qhEDPyqAmQf8Q+cVbXRyoVSoB5swWvUT2NYs/xSQd+QRt+u1WxM+lY4sVzMmp0TLDg4GYjJPbBQ7hdXkOj8R7xaRJVgUSAdOtPPK6Rlxm5pZnk08NL0lrt7bIRAq3PrW3YUuQvHN0ONw/bGXk8S6k2oyO5Ow1AeVNkhzPEaEaN3MDOIS1eA5lUe/8l7NkUgaKegmiQnZixEWZHQbaTPzTIj5Y1iPRBDh4M4uVaOVc1TYvj4C1dgkv6C/kz/PMLB4HVHl2B/ZkvwjSLMxCCE6N3U2kAncWB+nGW14MFn+H5LhZSO3UteXGYhuY9dNIbTtAvT5CaWLYGG1INP5mFf59c9cV+CD/f+JArkt0mCtZgSXDUOOFm74vbW2PdWB15PzWYJxGoHStbwOtJc1vttc0/RyzsomwpCDDaEhqDxWJSGC4DEllrtv8HTiJLvwtFLiPWWd0uj9ckSvWAyAn+9nJAbg9Axec/iedU9AhJbnavLKp8pPzcs=
